org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Correction des variables pour la 1.21.11
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.141.6+1.21.11

mod_version=1.0.0
maven_group=net.ely.auction
archives_base_name=donut_auction
